spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://서버DB주소:3306/moa
    username: 서버계정
    password: 서버비밀번호

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        "[format_sql]": false
        "[highlight_sql]": false

cors:
  allowed-origins: https://도메인주소

app:
  cookie:
    secure: true
    same-site: None

logging:
  level:
    org:
      hibernate:
        SQL: info
