spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moa
    username: team_moa
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": true
        "[highlight_sql]": true

cors:
  allowed-origins: http://localhost:5173
