spring:
  application:
    name: moa
  profiles:
    include: oauth2

jwt:
  secret: ${JWT_SECRET}
  access-exp-ms: 1800000
  refresh-exp-ms: 1209600000

app:
  cookie:
    secure: false
    same-site: Lax

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
