import type { CSSProperties } from 'react';

export const pageUi: Record<string, CSSProperties> = {
  boardWrap: {
    background: '#f6f7fb',
    border: '1px solid #e2e5ee',
    borderRadius: 14,
    padding: 14,
  },
  pageSection: {
    display: 'grid',
    gap: 14,
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
    padding: '4px 2px',
  },
  title: {
    margin: 0,
    fontSize: 28,
    letterSpacing: -0.3,
  },
  description: {
    margin: '6px 0 0',
    color: '#6b675f',
  },
  actions: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  boardTab: {
    padding: '7px 12px',
    borderRadius: 999,
    border: '1px solid #cfd5e2',
    background: '#fff',
    textDecoration: 'none',
    color: '#2a313f',
    fontSize: 13,
    fontWeight: 700,
  },
  boardTabActive: {
    border: '1px solid #212a3f',
    background: '#212a3f',
    color: '#fff',
  },
  actionLink: {
    padding: '8px 12px',
    borderRadius: 8,
    border: '1px solid #d9d4c7',
    background: '#fff',
    textDecoration: 'none',
    color: '#2b2925',
    fontSize: 13,
    fontWeight: 600,
  },
  actionButton: {
    padding: '8px 12px',
    borderRadius: 8,
    border: '1px solid #d9d4c7',
    background: '#fff',
    color: '#2b2925',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
  actionDanger: {
    padding: '8px 12px',
    borderRadius: 8,
    border: '1px solid #8f2f2f',
    background: '#8f2f2f',
    color: '#fff',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
  sectionCard: {
    border: '1px solid #e6dfcf',
    borderRadius: 12,
    background: '#fff',
    padding: 14,
  },
  mutedText: {
    margin: 0,
    color: '#666',
    fontSize: 13,
  },
  errorText: {
    color: 'crimson',
  },
  searchForm: {
    display: 'flex',
    gap: 8,
    padding: 10,
    border: '1px solid #d7dce8',
    borderRadius: 12,
    background: '#fff',
  },
  searchBarWrap: {
    position: 'sticky',
    top: 0,
    zIndex: 1,
    background: '#f6f7fb',
    paddingBottom: 8,
  },
  input: {
    flex: 1,
    border: '1px solid #cfd5e2',
    borderRadius: 10,
    padding: '10px 12px',
    fontSize: 14,
    outline: 'none',
    background: '#fff',
  },
  textarea: {
    border: '1px solid #cfd5e2',
    borderRadius: 10,
    padding: '10px 12px',
    fontSize: 14,
    resize: 'vertical',
    minHeight: 140,
  },
  buttonPrimary: {
    border: '1px solid #1f1f1f',
    borderRadius: 10,
    padding: '9px 14px',
    background: '#1f1f1f',
    color: '#fff',
    fontWeight: 700,
    cursor: 'pointer',
  },
  buttonPrimaryDisabled: {
    border: '1px solid #727784',
    borderRadius: 10,
    padding: '9px 14px',
    background: '#727784',
    color: '#f3f5f9',
    fontWeight: 700,
    cursor: 'default',
  },
  buttonGhost: {
    border: '1px solid #cfd5e2',
    borderRadius: 10,
    padding: '9px 12px',
    background: '#fff',
    cursor: 'pointer',
    color: '#4a5160',
    fontWeight: 600,
  },
  tableWrap: {
    border: '1px solid #d7dce8',
    borderRadius: 12,
    overflow: 'hidden',
    background: '#fff',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
  },
  tableHead: {
    background: '#eff2f8',
    color: '#2b3341',
    fontSize: 13,
    fontWeight: 700,
    textAlign: 'left',
  },
  tableHeadCell: {
    padding: '10px 12px',
    borderBottom: '1px solid #dfe4ef',
  },
  tableCell: {
    padding: '12px',
    borderBottom: '1px solid #eef1f6',
    color: '#2c313d',
    fontSize: 13,
  },
  tableCellNumeric: {
    padding: '12px',
    borderBottom: '1px solid #eef1f6',
    color: '#4a5060',
    fontSize: 13,
    textAlign: 'center',
    whiteSpace: 'nowrap',
  },
  tableRow: {
    background: '#fff',
  },
  tableTitleLink: {
    textDecoration: 'none',
    color: '#1e2431',
    fontWeight: 700,
    fontSize: 14,
  },
  cardMobile: {
    border: '1px solid #dce2ef',
    borderRadius: 12,
    padding: 12,
    background: '#fff',
    display: 'grid',
    gap: 6,
  },
  emptyState: {
    border: '1px dashed #d7dce8',
    borderRadius: 12,
    padding: 18,
    textAlign: 'center',
    color: '#5e6678',
    background: '#fff',
  },
  cardMetaRow: {
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
    fontSize: 12,
    color: '#5f6676',
  },
  metaBar: {
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
    alignItems: 'center',
    margin: '0 0 12px',
    color: '#50586a',
    fontSize: 13,
    borderBottom: '1px solid #e3e7f1',
    paddingBottom: 10,
  },
  contentBody: {
    margin: 0,
    whiteSpace: 'pre-wrap',
    color: '#2f3441',
    lineHeight: 1.72,
    fontSize: 15,
  },
  chip: {
    border: '1px solid #d2d8e6',
    borderRadius: 999,
    padding: '2px 8px',
    background: '#fff',
    fontSize: 12,
    color: '#3c4454',
  },
  paginationWrap: {
    display: 'flex',
    gap: 6,
    alignItems: 'center',
    marginTop: 14,
    paddingTop: 12,
    borderTop: '1px solid #dde2ee',
  },
  paginationInfo: {
    marginLeft: 10,
    fontSize: 13,
    color: '#5d6578',
  },
  form: {
    display: 'grid',
    gap: 10,
  },
  formLabel: {
    fontSize: 13,
    fontWeight: 700,
    color: '#303747',
  },
  paginationButton: {
    border: '1px solid #cfd5e2',
    borderRadius: 10,
    padding: '6px 10px',
    background: '#fff',
    color: '#2f3646',
    cursor: 'pointer',
  },
  paginationButtonDisabled: {
    border: '1px solid #e1e5ef',
    borderRadius: 10,
    padding: '6px 10px',
    background: '#f2f4f9',
    color: '#9aa1b2',
    cursor: 'default',
  },
  paginationButtonActive: {
    border: '1px solid #1f2a44',
    borderRadius: 10,
    padding: '6px 11px',
    background: '#1f2a44',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: 700,
  },
  breadcrumbLink: {
    textDecoration: 'none',
    color: '#6b675f',
    fontWeight: 600,
  },
  asideTitle: {
    margin: 0,
    fontSize: 14,
    color: '#2b2925',
  },
  asideMuted: {
    margin: 0,
    fontSize: 13,
    color: '#6b675f',
    lineHeight: 1.5,
  },
};
